### ISSUE TITLE
Opencore 0.8.8 can’t show eMMC partition 

### ISSUE THREAD

**Issue by tranmylinhvn** [meghan06/ChromebookOSX#3]
After I finish installed Catalina on eMMC,Installer had reboot and can not show any partition on eMMC, I had tried copy EFI folder from USB installer and boot from eMMC but the result is same. Please help me to fix it.
![image](https://user-images.githubusercontent.com/85661932/218307971-4c190e0b-eb9b-41c3-a9ae-360d6e232f2b.jpg)

**Comment by meghan06** [comment]
probably a configuration issue since everyone I know doesn't have this issue. Start by deleting all the tools, you don't need them

**Comment by meghan06** [comment]
Unable to replicate, maybe try macOS 11 or newer.
