### ISSUE TITLE
AppleSMC & AppleAHCIDiskDriver Panic

### ISSUE THREAD

**Issue by catfamily121** [meghan06/ChromebookOSX#9]
**Describe the issue**
Kernel Panic on boot of the recovery USB

**To Reproduce**
1. Follow the Dortaina guide for getting the BaseSystem.dmg via macrecovery.py
2. Create the config.plist
3. Make adjustments to config.plist that are not mentioned in the Dortaina guide
4. Boot the USB

**Expected behavior**
Catalina boots & installs to another USB drive as my SSD is only 16GB

**Screenshots**
![20230311_151333](https://user-images.githubusercontent.com/124477943/224517130-570518d5-de4f-489d-9896-35b6cfd56247.jpg)

**Versions (please complete the following information):**
 - OS: macOS 10.15, hoping to get Big Sur once this boots
 - OC Version: 0.9
 - Mr Chromebox Firmware: 4.12

**Device (please complete the following information):**
 - Device: Dell Chromebook 13 7310 (LULU)
**Additional context**
[EFI 2.zip](https://github.com/meghan06/ChromebookOSX/files/10949737/EFI.2.zip)

I have also made an issue on [one8three/Hackintosh---Dell-Chromebook-13-7310](https://github.com/one8three/Hackintosh---Dell-Chromebook-13-7310), but that repo hasn't been updated in years and I truly doubt that someone would respond. Here is my EFI after contacting the nice people at the hackintosh & chrultrabook discord.

**Comment by meghan06** [comment]
You should update your UEFI. Unfortunately I am unable to provide support for devices other than board name LEONA due to the lack of knowledge.
